server:
  port: 8081
  
spring:
  application:
    name: trainer-service
  datasource:
    port: 3306
    url: jdbc:mysql://localhost:3306/ProjectPokemonTrainers
    database: ProjectPokemonTrainers
    username: root
    password: root
    ssl: false